### ISSUE TITLE
[III] Оставшаяся бизнес-логика

### ISSUE THREAD

**Issue by ABaranovskiy** [BaranovskyA/ByteBrew-Coffee-Roasters#14]
Сделать функционал страницы "Меню" для пользователей, с возможность добавлять в корзину, удалять из корзины, а также уменьшать и увеличивать количество товара в корзине. Хранить добавленные товары нужно в БД, ключ к содержимому корзины хранить в куках. Пользователи без учетной записи тоже должны иметь возможность добавлять в корзину.

Сделать функционал страницы "Корзина" для пользователей. Корзина должна иметь тот же функционал по взаимодействию с количеством товара, что и меню. Снизу страницы должна отображаться сумма к оплате, составленная из количества каждого товара умноженного на его цену. В самом низу отображается кнопка "Оформить заказ", после нажатия на нее создается запись в таблице Заказы со статусом "Создан" и очищается корзина.

Сделать функционал страницы "Заказы" для менеджеров и администраторов. На странице должны отображаться заказы со статусом "Создан" в виде таблицы. Пользователь должен иметь возможность отметить каждый заказ как выполненный, после чего его статус меняется на "Выполнен" и он не отображается на странице, но остается в БД.

**Comment by AveApollyon** [comment]
Самый быстрый бэкендер на диком западе

**Comment by AveApollyon** [comment]
Самый быстрый бэкендер на диком западе
