### ISSUE TITLE
[III] Наводим красоту

### ISSUE THREAD

**Issue by ABaranovskiy** [BaranovskyA/ByteBrew-Coffee-Roasters#15]
Все элементы страницы должны соответствовать общей стилистике сайта, выглядеть эстетично и интуитивно понятно.

Страница "Меню":
- [x] Товары должны отображаться в виде грида, по 2 в одной строке.
- [x] В каждой карточке должно отображаться: название товара, описание, картинка, цена.
- [x] Под ценой отображается количество товара в корзине и должны быть кнопки управления корзиной: +, -, удалить все.

Страница "Корзина":
- [x] Товары отображаются в виде прямоугольной карточки по одному в строке.
- [x] В левом углу карточки находится превью картинки товара.
- [x] Внешний вид элементов для управления корзиной примерно повторяет тот, который на странице "Меню".

Страница "Заказы":
- [x] Заказы отображаются в виде таблицы.
- [x] В каждом заказе отображается статус пользователя (авторизован, анонимный), дата заказа, статус заказа, состав заказа и кнопка для выполнения заказа.
- [x] Внешний вид элементов для управления заказами примерно повторяет тот, который на странице "Продукты".

Страница "Отзывы к товарам" для пользователей:
- [x] Создать страницу, которая позволяет пользователям оставлять отзывы к товарам.
- [x] Товары на странице отображаются в виде таблицы.

Страницы "Отзывы к товарам" для менеджеров и администраторов:
- [x] Создать страницу, которая позволяет администраторам просматривать отзывы, которые оставили пользователи.
- [x] Доступ к странице должен быть только у пользователей с ролью "Менеджер" или "Администратор".
- [x] Должна быть возможность удалять отзывы.
- [x] Отзывы должны отображаться в виде таблицы.

**Comment by AveApollyon** [comment]
![bebravovach](https://github.com/BaranovskyA/ByteBrew-Coffee-Roasters/assets/52245082/ecddd64b-af33-4d79-9717-8e763196487a)
